name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=taylorteixeira_devops--satc
            -Dsonar.organization=taylorteixeira
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=taylorteixeira_devops--satc
            -Dsonar.organization=taylorteixeira
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/satc-devops:0.0.2 .

      - name: Push Docker image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/satc-devops:0.0.2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'docker.io/taylorteixeira/satc-devops:0.0.2'
          format: json
          output: trivy-results.json
          severity: MEDIUM,HIGH,CRITICAL

      - name: Upload Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results.json
          path: trivy-results.json

      - name: Analyze Trivy results
        run: |
          if [ -f trivy-results.json ]; then
            VULN_COUNT=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "MEDIUM")] | length' trivy-results.json)
            echo "Quantidade de vulnerabilidades mÃ©dias: $VULN_COUNT"

            if [ "$VULN_COUNT" -gt 2 ]; then
              echo "Pipeline bloqueada: mais de 2 vulnerabilidades mÃ©dias encontradas."
              exit 1
            fi
          else
            echo "Arquivo de resultados do Trivy nÃ£o encontrado."
            exit 1
          fi

      - name: Falhar se houver mais de 2 vulnerabilidades mÃ©dias
        run: |
          COUNT=$(curl -s -u "${SONNAR_TOKEN}:" \
            "https://sonarcloud.io/api/issues/search?componentKeys=${SONNAR_PROJECT_KEY}&types=VULNERABILITY&severities=MAJOR&resolved=false&ps=1" \
            | jq '.total')

          echo "Quantidade de vulnerabilidades mÃ©dias: $COUNT"

          if [ "$COUNT" -gt 2 ]; then
            echo "Pipeline bloqueada: mais de 2 vulnerabilidades mÃ©dias encontradas."
            exit 1
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: taylorteixeira
